model:
  base_learning_rate: 0.0001
  target: custom.cldm.ControlLDM
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    #
    first_stage_key: image
    #
    cond_stage_key: txt
    control_key: fmri
    image_size: 64
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss
    use_ema: False
    only_mid_control: False
    
    control_stage_config:
      target: custom.cldm.ControlNet
      params:
        image_size: 64
        #ControlNet 为什么c=4
        in_channels: 4
        hint_channels: 3
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        #context_dim: 320
        use_checkpoint: True
        legacy: False

    unet_config:
      target: custom.cldm.ControlledUnetModel
      params:
        image_size: 64
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        cond_scale: 1.0
        use_time_cond: false
        global_pool: false
    
    first_stage_config:
      target: dc_ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    cond_stage_config:
      target: dc_ldm.modules.encoders.modules.FrozenCLIPEmbedder